### PR TITLE
Tests

### LINKED ISSUE #27: Add tests
Add tests for basic functionality and async render queue.

### PR DESCRIPTION
**Pull request by programmer4web**
basic tests (defaults, properties update, cache, other methods, elements buffer, renderQueue). resizable test.
fixes https://github.com/Neovici/cosmoz-data-nav/issues/27

### CODE REVIEW

**Review by nomego — APPROVED** [review]

**Comment by nomego** [comment]
Tests should pass before merging though (I don't review the actual tests..)

**Review by plequang — APPROVED** [review]
Looks good.
Is still WIP ?

**Comment by programmer4web** [comment]
@plequang   For the moment the test are alright but with the Hash-param https://github.com/Neovici/cosmoz-data-nav/pull/36 changes will need to be done.

**Comment by nomego** [comment]
Let's rebase and merge?

**Comment by programmer4web** [comment]
@nomego I have rebased the tests and added some fixes to work with hash-param updates. If you can restart the build on travis-ci it will be great.

**Comment by nomego** [comment]
@programmer4web ready to merge or still wip?

**Comment by programmer4web** [comment]
@nomego Ready to merge.

**Pull request merged**
