### PR TITLE
Handles multiple items with the same

### PR DESCRIPTION
**Pull request by megheaiulian**
Handles multiple items with the same.

Fixes loop issue in frontend.

### CODE REVIEW

**Comment by nomego** [comment]
Any reason why we shouldn't just set the object for all matching items?

**Comment by megheaiulian** [comment]
If more than one item matches we find the first incomplete one and if only one matches we replace it directly.

**Comment by nomego** [comment]
Ok. Why did we request details about the second instance? Is this fixed now or is there somewhere else we should use the cache?

**Comment by nomego** [comment]
Can we also add tests for this, multiple same-id items? Making sure we only request details once and not loop?

**Comment by megheaiulian** [comment]
There was a loop because in setitembyid it was find the same item by ID again and again. Now if there are more matches it grabs the first incomplete one.

**Comment by megheaiulian** [comment]
Refactored the code and now it won't load twice items with the same id.

**Comment by nomego** [comment]
Why do you copy the object? I think it would beneficial for memory and links to just reference the same object?

**Comment by megheaiulian** [comment]
We copy the object so that it is a different one. If two identical items are in the array `indexOf` might return a unexpected index. There isn't much performance issues with that  because object keys are not deeply extended so sub-key still keep their references.

**Review by nomego — APPROVED** [review]
Ok! Sounds good. We might want to document that somewhere and also add some tests surrounding this.

**Comment by megheaiulian** [comment]
I will add tests for this.

**Pull request merged**
